version: '4.13'

services:
  backend:
    image: 'yedilbakenov/docker-test-g132'
    container_name: 'test-container'
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8082:8080

  db:
    image: 'postgres'
    container_name: 'postgres-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 2444:5432


